---
engine_version: 0.4.2
file_version: 2022-12-09 06:31:18.200122000 Z
resources:
- name: character
  preferences:
    columns:
    - column_type: richtext
      name: long_description
  updated_at: 2022-12-09 06:31:18.200122000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2022-12-09 06:30:02.836646000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2022-12-09 06:30:02.841170000 +00:00
