---
engine_version: 0.4.2
file_version: 2022-12-09 06:22:06.217975000 Z
resources: []
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  updated_at: 2022-12-09 06:22:06.217975000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2022-12-09 06:18:38.933290000 +00:00
