import Head from 'next/head'
import Link from 'next/link'
import Button from './components/button'
import { useState } from 'react'

export default function Index() {
  const title = 'Compendium'
  const [defaultVisibility, setDefaultVisibility] = useState(true)
  const [registerVisibility, setRegisterVisibility] = useState(false)
  const [loginVisibility, setLoginVisibility] = useState(false)

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <img src="/header_logo.png" className="m-auto" width={420}></img>
      <div className="mx-6 mt-4">
        <h1 className="text-4xl font-bold font-serif pt-10 px-4">Crie seu Personagem</h1>
        <p className="mt-5 text-sm px-4">
          Criar um personagem do zero no
          <span className="font-bold"> Fábulas &amp; Goblins </span>
           é muito fácil, basta criar uma conta e gerar
          seus personagens com poucos cliques!
        </p>

        {defaultVisibility && (
          <div className="px-4">
            <div className="mt-5">
              <Button onClick={e => {
                setDefaultVisibility(false)
                setRegisterVisibility(true)
                setLoginVisibility(false)
              }}>
              Crie sua Conta
              </Button>
            </div>
            <div className="mt-5 pb-5">
              <Button onClick={e => {
                setDefaultVisibility(false)
                setRegisterVisibility(false)
                setLoginVisibility(true)
              }}>
              Entrar
              </Button>
            </div>
          </div>
        )}

        {loginVisibility && (
          <LoginForm />
        )}
      </div>
    </div>
  )
}
