import Head from 'next/head'
import Button from './components/button'
import LoginForm from './components/login'
import RegisterForm from './components/register'
import { useState } from 'react'

export default function Index() {
  const title = 'Compendium'
  const [visibility, setVisibility] = useState({
    register: false,
    login: false
  })

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <img src="/header_logo.png" className="m-auto" width={420}></img>
      <div className="mx-6 mt-4">
        <h1 className="text-4xl font-bold font-serif pt-10 px-4">{title}</h1>
        <p className="mt-5 text-sm px-4">
          Aqui você encontra todo o conteúdo que criamos para vc usar em suas aventuras dentro do universo do
          <span className="font-bold"> Fábulas &amp; Goblins</span>.
        </p>

        {!visibility.login && !visibility.register && (
          <div className="px-4">
            <div className="mt-5">
              <Button onClick={e => {
                setVisibility({
                  register: true,
                  login: false
                })
              }}>
              Registrar
              </Button>
            </div>
            <div className="mt-5 pb-5">
              <Button onClick={e => {
                setVisibility({
                  register: false,
                  login: true
                })
              }}>
              Entrar
              </Button>
            </div>
          </div>
        )}

        {visibility.login && (
          <div>
            <LoginForm onCancel={e => {
              setVisibility({
                register: false,
                login: false
              })
            }
            }></LoginForm>
          </div>
        )}

        {visibility.register && (
          <div>
            <RegisterForm></RegisterForm>
            <Button className="mt-5" onClick={e => {
              setVisibility({
                register: false,
                login: false
              })
            }}>
              Cancelar
            </Button>
          </div>
        )}
      </div>
    </div>
  )
}
