import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Spell from 'src/components/spell'
import { useRouter } from 'next/router'

export default function Index() {
  const title = 'Poderes'
  const [spell, setSpell] = useState(null)

  const router = useRouter()
  const permalink = router.query.permalink

  useEffect(() => {
    async function loadSpells(page) {
      const result = await fetch(`http://localhost:5000/api/spells?q[permalink_cont]=${router.query.permalink}`)
      const response = await result.json()
      setSpell(response[0])
    }

    if (permalink) {
      loadSpells()
    }
  }, [permalink])

  if (!spell) return;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Spell spell={spell} />
    </div>
  )
}
