import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import * as Icons from 'react-icons/gi'
import Spell from 'src/components/spell'

export default function Print() {
  const title = 'Poderes'
  const [spells, setSpells] = useState([])

  useEffect(() => {
    async function loadSpells(page) {
      const result = await fetch(`http://localhost:5000/api/spells?page=1`)
      const response = await result.json()
      setSpells(response)
      const totalPages = result.headers.get('X-Pages') || ''
      const totalPagesParsed = parseInt(totalPages, 10)
    }

    loadSpells()
  }, [])

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="mx-3 md:mx-6 mt-4">
        <div className='grid grid-cols-2 gap-6'>
          {spells.map(spell => {
            const Icon = Icons[spell.icon]

            return (
              <div className="">
                <Spell spell={spell} />
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
